<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Tarkovy</AssemblyName>
    <RootNamespace>Tarkovy</RootNamespace>
    <Version>0.0.4</Version>
    <FileVersion>0.0.4.0</FileVersion>
    <AssemblyVersion>0.0.4.0</AssemblyVersion>
    <InformationalVersion>Dev 0.0.4</InformationalVersion>
    <AssemblyTitle>Dev 0.0.4</AssemblyTitle>
    <ApplicationTitle>Tarkovy</ApplicationTitle>
    <Product>Tarkovy</Product>
    <Title>Dev 0.0.4</Title>
    <Company>Anomaly Labs</Company>
    <Authors>Anomaly Labs</Authors>
    <Copyright>Copyright © Anomaly Labs</Copyright>
    <Description>Minimapa overlay para Escape from Tarkov · Anomaly Labs</Description>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\brand\tarkovy.ico</ApplicationIcon>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**\*" Exclude="Assets\brand\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\**\*" Exclude="Assets\brand\**\*" />
    <Resource Include="Assets\brand\tarkovy.ico" />
    <Resource Include="Assets\brand\tarkovy-icon.png" />
    <Resource Include="Assets\brand\tarkovy-icon-256.png" />
    <Resource Include="Assets\brand\tarkovy-logo.png" />
  </ItemGroup>
  <PropertyGroup>
    <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

</Project>
