<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Tarkovy</AssemblyName>
    <RootNamespace>Tarkovy</RootNamespace>
    <Version>0.1.8</Version>
    <FileVersion>0.1.8.0</FileVersion>
    <AssemblyVersion>0.1.8.0</AssemblyVersion>
    <InformationalVersion>Dev 0.1.8</InformationalVersion>
    <AssemblyTitle>Dev 0.1.8</AssemblyTitle>
    <ApplicationVersion>0.1.8.0</ApplicationVersion>
    <ApplicationTitle>Tarkovy</ApplicationTitle>
    <Product>Tarkovy</Product>
    <Title>Dev 0.1.8</Title>
    <Company>Anomaly Labs</Company>
    <Authors>Anomaly Labs</Authors>
    <Copyright>Copyright © Anomaly Labs</Copyright>
    <Description>Minimapa overlay para Escape from Tarkov · Anomaly Labs</Description>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\brand\tarkovy.ico</ApplicationIcon>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishSingleFile)' == 'true'">
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup Condition="'$(PublishSingleFile)' != 'true'">
    <Content Include="Assets\**\*" Exclude="Assets\brand\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*" Exclude="Assets\brand\**\*" />
    <Resource Include="Assets\brand\tarkovy.ico" />
    <Resource Include="Assets\brand\tarkovy-icon.png" />
    <Resource Include="Assets\brand\tarkovy-icon-256.png" />
    <Resource Include="Assets\brand\tarkovy-logo.png" />
  </ItemGroup>
  <PropertyGroup>
    <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

</Project>
